services:
  lb:
    build: .
    command: ["java", "-cp", "out", "lb.LoadBalancer"]
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: .
    command: ["java", "-cp", "out", "lb.SimpleServer", "1", "3001"]

  server2:
    build: .
    command: ["java", "-cp", "out", "lb.SimpleServer", "2", "3002"]

  server3:
    build: .
    command: ["java", "-cp", "out", "lb.SimpleServer", "3", "3003"]

  dashboard:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/lb/dashboard.html:/usr/share/nginx/html/index.html