services:

  lb:
    build: .
    container_name: load-balancer
    command: ["java", "-cp", "out", "lb.LoadBalancer"]
    ports:
      - "8080:8080"


  dashboard:
    image: nginx:alpine
    container_name: lb-dashboard
    ports:
      - "3000:80"
    volumes:
      - ./src/lb/dashboard.html:/usr/share/nginx/html/index.html